shellcheck

diff --git a/bin/n b/bin/n
--- a/bin/n
+++ b/bin/n
@@ -1,23 +1,23 @@
 #!/bin/bash
 
 # Check if the notes exist
-[[ -d $NOTES_PATH ]] || (echo "Notes not found at:  $NOTES_PATH" ; exit 1)
+[[ -d "$NOTES_PATH" ]] || (echo "Notes not found at:  $NOTES_PATH" ; exit 1)
 
 # Skip collection if the file exists.
-if [ -f "$NOTES_PATH/$1" ]; then
+if [[ -f "$NOTES_PATH/$1" ]]; then
 	FILE=$1
 else
 	# Pull Subject from CLI.
 	test -n "$*" && SUBJECT="$*"
 	# Read the subject
-	test -n "$*" || read -p "Note title: " SUBJECT
+	test -n "$*" || read -rp "Note title: " SUBJECT
 	# Format as slug.
-	SLUG=$(echo $SUBJECT | sed -r s/[^a-zA-Z0-9]+/-/g | tr A-Z a-z)
+	SLUG="$(echo "$SUBJECT" | sed -r s/[^a-zA-Z0-9]+/-/g | tr "[:upper:]" "[:lower:]")"
 	# Get file name.
-	FILE=$(date +%Y-%m-%d-$SLUG.md)
+	FILE="$(date +%Y-%m-%d)-$SLUG.md"
 fi
 # Jump into our Notes repo.
-cd $NOTES_PATH
+cd "$NOTES_PATH" || exit
 # Git pull, but do it in the background.
 git pull -q &
 
@@ -30,15 +30,15 @@ tags:
 ---
 
 Have fun writing about $SUBJECT!"
-[[ -f $FILE ]] || echo "$TEMPL" >> $FILE
-if [ ! -z "$TMUX" ]; then
+[[ -f "$FILE" ]] || echo "$TEMPL" >> "$FILE"
+if [[ -n "$TMUX" ]]; then
 	tmux run "echo #{pane_id}" > ~/.notes_pane
-	basename $FILE > ~/.notes_pane.title
+	basename "$FILE" > ~/.notes_pane.title
 fi
 # Alias for edit and commit.
-editor-and-commit $FILE
+editor-and-commit "$FILE"
 [[ -z "$TMUX" ]] || rm -f ~/.notes_pane*
 # Push it real good! /snp
 git push -q
 # Change back to the previous directory.
-cd - 1>/dev/null
+cd - 1>/dev/null || exit
